### ISSUE TITLE
ESP Crash

### ISSUE THREAD

**Issue by EMBYRDEV** [Open-CK/OpenCK#8]
The attached ESP file causes OpenCK to crash. 

[1nivWICCloaksCRAFT.zip](https://github.com/Open-CK/OpenCK/files/1812299/1nivWICCloaksCRAFT.zip)

**Comment by Adam-Gleave** [comment]
Interesting, do you know what record is being parsed when it crashes? It sounds like some buffer pointer is being thrown off.

**Comment by EMBYRDEV** [comment]
Not a clue, was too tired to look into it (as evidenced by my mindless UI tweaking today) so figured I'd stick it here for others or myself to follow up on.

**Comment by Adam-Gleave** [comment]
No worries, thanks for identifying it!

**Comment by Smifferz** [comment]
Done a bit of research into this, the issue comes from FormFactory. 
We don't seem to support some type codes being returned by .esp files so they are failing with access violations to areas of memory due to newForm hanging onto some random area of memory.

From the couple of .esp files I've tried I have seen type codes "ARMO" and "ENCH".

**Comment by Adam-Gleave** [comment]
Oh I see. That's because we were just working on Skyrim.esm and setting the parser to stop after getting past a certain record. If a .esp/.esm doesn't contain any of those records, it will cause this bug.

Should be an easy fix, just need to add a default case in FormFactory and a way to handle that object when it is returned.

**Comment by Malrama** [comment]
Fixed for now! (♡˙︶˙♡) Can be closed

**Comment by Adam-Gleave** [comment]
Sorted. Just need to have some kind of dialog or warning, but it no longer crashes. Nice work.
